// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgvjDRiTOxqCJZUQ58ud9CBDBZnRNZCLU',
    appId: '1:150389108065:web:91c8cce3954a30061ce920',
    messagingSenderId: '150389108065',
    projectId: 'fcmtest-8658e',
    authDomain: 'fcmtest-8658e.firebaseapp.com',
    storageBucket: 'fcmtest-8658e.appspot.com',
    measurementId: 'G-YYNGXYHJZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt2MnMC9zm2rifE01k5DUc4kLs28RDrVE',
    appId: '1:150389108065:android:7f80e8be58303a731ce920',
    messagingSenderId: '150389108065',
    projectId: 'fcmtest-8658e',
    storageBucket: 'fcmtest-8658e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK7M18O4inRfxaK7tVUq9krgOCWch9Gng',
    appId: '1:150389108065:ios:f4604bd336a6c26e1ce920',
    messagingSenderId: '150389108065',
    projectId: 'fcmtest-8658e',
    storageBucket: 'fcmtest-8658e.appspot.com',
    iosClientId: '150389108065-5j7tsudjj6hnpfl8mdctqhlkrl9ci66t.apps.googleusercontent.com',
    iosBundleId: 'com.example.teleconsultation',
  );
}
